permalink: /:title/
relative_permalinks: false
markdown: kramdown
future: false
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
kramdown:
  footnote_backlink: "&#8617;&#xFE0E;"